### ISSUE TITLE
NullReferenceException for Friend NPC

### ISSUE THREAD

**Issue by SharonLougheed** [SharonLougheed/DrearilyDreaming#22]
NullReferenceException: Object reference not set to an instance of an object
CELL.get_randomPointOfInterest () (at Assets/01_Scripts/01_Monobehaviors/00_Generic/CELL.cs:52)
NPC.Change_Point_Of_Interest (.CELL_ENTITY _newPointOfInterest) (at Assets/01_Scripts/01_Monobehaviors/00_Generic/NPC.cs:57)
NPC+<Idle>c__Iterator1.MoveNext () (at Assets/01_Scripts/01_Monobehaviors/00_Generic/NPC.cs:254)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)

**Comment by ACowboyKiller** [comment]
So, you assigned the wrong Chris.  However, this should be resolved now.
